[package]
name = "echars"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12.0"
csv = "1.1.6"
serde = { version = "1", features = ["derive"] }
directories = "4.0"
anyhow = "1.0.55"