[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
scrapper = {path = "../scrapper"}
anyhow = "1.0.55"
directories = "4.0"
serde = { version = "1", features = ["derive"] }
csv = "1.1.6"
